### ISSUE TITLE
Possibility of this working with git

### ISSUE THREAD

**Issue by samaursa** [learn-computer-graphics/perforce-uasset-diff#1] opened 2024-03-20 20:39 UTC
When running from Fork (a git client) it seems that I am _almost_ all the way there. The script window pops up, closes without error and Unreal appears to get the following command:

```
2024.03.20-13.31.24 [DESKTOP] 00088.182: Cmd: diff D:\MyRepo\MyAsset_BP.uasset C:\Users\myusername\AppData\Local\Temp\Fork\staged\MyAsset_BP.uasset
```

But nothing happens. No error in Unreal logs either. Just the above console log. I don't know what I _should_ see in the logs to compare.

**Comment by guillaume-haerinck** [comment] 2024-03-20 22:30
Hey ! I checked the source code of Unreal 5.3 and wasn't able to find the runtime registration of the diff command, which is super weird as I was using this all the time with the main version of Unreal 5 a few month back. I'll make a basic plugin to register `UAssetToolsImpl::DiffAssets()` as a command so that there is always a fallback.

It is possible to launch unreal with the -diff command as seen via the code path `EditorCommandLineUtilsImpl::RunAssetDiffCommand`, but its not ideal as it will relaunch the engine anytime you need to do a diff

**Comment by samaursa** [comment] 2024-03-20 22:46
Awesome, thanks! Looking forward to that addition

> It is possible to launch unreal with the -diff command as seen via the code path EditorCommandLineUtilsImpl::RunAssetDiffCommand, but its not ideal as it will relaunch the engine anytime you need to do a diff

Yes. It is indeed very slow since it launches UE every time.

**Comment by guillaume-haerinck** [comment] 2024-04-27 09:07
Closing as a duplicate of https://github.com/learn-computer-graphics/perforce-uasset-diff/issues/2, the repo now has the diff plugin and the doc will be updated to show how to use it with git (similar to https://gist.github.com/Panakotta00/c90d1017b89b4853e8b97d13501b2e62)

**Closed by guillaume-haerinck** 2024-04-27 09:07 UTC
